sonar.projectKey=Frontend-ELearning
sonar.projectName=Frontend E-Learning
sonar.host.url=http://localhost:9000
sonar.sourceEncoding=UTF-8

sonar.sources=app,components,hooks,lib,store,proxy.ts
sonar.tests=Sprint-2&3-Tests,Sprint-5-Tests,S5-TESTS
sonar.test.inclusions=**/*.spec.ts,**/*.test.ts,**/*.test.tsx
sonar.exclusions=node_modules/**,.next/**,public/**,coverage/**,**/playwright-report/**,**/test-results/**
